name: Go Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Go Binary
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        arch: [amd64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Set environment variables
      run: |
        # Set GOOS based on matrix.os
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          echo "GOOS=windows" >> $GITHUB_ENV
        elif [ "${{ matrix.os }}" == "macos-latest" ]; then
          echo "GOOS=darwin" >> $GITHUB_ENV
        elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          echo "GOOS=linux" >> $GITHUB_ENV
        fi

        # Set GOARCH based on matrix.arch
        if [ "${{ matrix.arch }}" == "amd64" ]; then
          echo "GOARCH=amd64" >> $GITHUB_ENV
        elif [ "${{ matrix.arch }}" == "arm64" ]; then
          echo "GOARCH=arm64" >> $GITHUB_ENV
        fi

    - name: Build
      run: |
        mkdir -p dist/${{ matrix.os }}-${{ matrix.arch }}
        binary_name="notebrew"
        if [ "${{ env.GOOS }}" == "windows" ]; then binary_name="notebrew.exe"; fi
        go build -ldflags '-w' -tags open_browser,fts5 -trimpath -o dist/${{ matrix.os }}-${{ matrix.arch }}/${binary_name} ./notebrew

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: notebrew-${{ matrix.os }}-${{ matrix.arch }}
        path: dist/${{ matrix.os }}-${{ matrix.arch }}/notebrew*

  release:
    name: Create Release and Upload Binaries
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download binaries
      uses: actions/download-artifact@v4
      with:
        name: notebrew-${{ matrix.os }}-${{ matrix.arch }}

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload to Release
      run: |
        for os_arch in $(ls dist); do
          gh release upload ${{ github.ref }} dist/$os_arch/notebrew* --clobber
        done
